// module.exports = ['Bradesco', ' Burger King', ' Leroy Merlin', ' Meio & Mensagem', 'Faber Castell', 'Unilever', 'Kota', 'Ale'];
module.exports = [
  { year: 2016, brand: 'Instituto Aria', fullBrand: 'Instituto Aria' },
  { year: 2016, brand: 'Kota', fullBrand: 'Kota', featured: true },
  { year: 2016, brand: 'Oral Quartz', fullBrand: 'Oral Quartz' },
  { year: 2016, brand: 'Quickcheck', fullBrand: 'Quickcheck' },
  { year: 2016, brand: 'Artwork', fullBrand: 'Artwork by Tikun' },
  { year: 2016, brand: 'JPLAY', fullBrand: 'JPLAY', featured: true },
  { year: 2016, brand: 'JC', fullBrand: 'JC Estética Dentária' },
  { year: 2016, brand: 'Garófalo', fullBrand: 'Garófalo Cursos' },
  { year: 2016, brand: 'Signature', fullBrand: 'Signature', featured: true },
  { year: 2016, brand: 'Implanteperio', fullBrand: 'Implanteperio', featured: true },
  { year: 2016, brand: 'Vasconcelos', fullBrand: 'Vasconcelos Odontologia' },
  { year: 2016, brand: 'A&D', fullBrand: 'A&D' },
  { year: 2017, brand: 'Epson', fullBrand: 'Epson' },
  { year: 2017, brand: 'Samsung', fullBrand: 'Samsung' },
  { year: 2017, brand: 'Burger King', fullBrand: 'Burger King', featured: true },
  { year: 2017, brand: 'Faber Castell', fullBrand: 'Faber Castell', featured: true },
  { year: 2017, brand: 'Leroy Merlin', fullBrand: 'Leroy Merlin', featured: true },
  { year: 2017, brand: 'Zap Imóveis', fullBrand: 'Zap Imóveis' },
  { year: 2017, brand: 'Meio & Mensagem', fullBrand: 'Meio & Mensagem', featured: true },
  { year: 2017, brand: 'KES', fullBrand: 'KES' },
  { year: 2017, brand: 'Unilever', fullBrand: 'Unilever', featured: true },
  { year: 2018, brand: 'Ale', fullBrand: 'Ale', featured: true },
  { year: 2018, brand: 'TNC', fullBrand: 'TNC', featured: true },
  { year: 2018, brand: 'MamyPoko', fullBrand: 'MamyPoko', featured: true },
  { year: 2019, brand: 'Bradesco', fullBrand: 'Bradesco', featured: true },
  { year: 2022, brand: 'Bradescard', fullBrand: 'Bradescard', featured: true },
];
