module.exports = {
  weekday: [
    { startTime: '23:00', endTime: '23:59', message: 'sleeping', status: 'offline' },
    { startTime: '00:00', endTime: '7:59', message: 'sleeping', status: 'offline' },
    { startTime: '8:00', endTime: '8:29', message: 'having breakfast', status: 'away' },
    { startTime: '8:30', endTime: '9:29', message: 'went to gym', status: 'away' },
    { startTime: '9:30', endTime: '9:59', message: 'reading my emails', status: 'available' },
    { startTime: '10:00', endTime: '12:29', message: 'programming', status: 'available' },
    { startTime: '12:30', endTime: '13:59', message: 'having lunch', status: 'away' },
    { startTime: '14:00', endTime: '5:29', message: 'programming', status: 'available' },
    { startTime: ':5:30', endTime: '16:59', message: 'in a call or meeting', status: 'busy' },
    { startTime: '17:00', endTime: '17:29', message: 'taking a walk', status: 'away' },
    { startTime: '17:30', endTime: '17:59', message: 'watching the news', status: 'available' },
    { startTime: '18:00', endTime: '18:59', message: 'programming', status: 'available' },
    { startTime: '19:00:', endTime: '19:59', message: 'having dinner', status: 'away' },
    { startTime: '20:00:', endTime: '20:59', message: 'working in some personal project', status: 'busy' },
    { startTime: '21:00', endTime: '21:29', message: 'doing skincare', status: 'away' },
    { startTime: '21:30', endTime: '21:59', message: 'watching soap opera or bbb', status: 'away' },
    { startTime: '22:00', endTime: '22:59', message: 'reading a book', status: 'away' },
  ],
  saturday: [
    { startTime: '00:00', endTime: '8:59', message: 'sleeping', status: 'offline' },
    { startTime: '9h:00', endTime: '11:59', message: 'having breakfast (pastel)', status: 'away' },
    { startTime: '12:00', endTime: '12:59', message: 'studying', status: 'busy' },
    { startTime: '13:00', endTime: '18:59', message: 'hanging out with friends or family', status: 'busy' },
    { startTime: '19:00', endTime: '21:59', message: 'having a drink', status: 'away' },
    { startTime: '22:00', endTime: '22:59', message: 'doing skincare', status: 'away' },
    { startTime: '23:00', endTime: '23:59', message: 'watching a series or movie', status: 'away' },
  ],
  sunday: [
    { startTime: '23:00', endTime: '23:59', message: 'sleeping', status: 'offline' },
    { startTime: '00:00', endTime: '9:59', message: 'sleeping', status: 'offline' },
    { startTime: '10:00', endTime: '10:59', message: 'having breakfast', status: 'away' },
    { startTime: '11:00', endTime: '14:59', message: 'riding bike or taking a walk', status: 'away' },
    { startTime: '15:00', endTime: '17:59', message: 'selfcare', status: 'away' },
    { startTime: '18:00', endTime: '19:59', message: 'reading', status: 'busy' },
    { startTime: '20:00', endTime: '20:59', message: 'watching tv', status: 'away' },
    { startTime: '21:00', endTime: '22:29', message: 'doing skincare', status: 'away' },
    { startTime: '22:30', endTime: '22:59', message: 'watching bbb', status: 'away' },
  ],
};
